-- =====================================================================
-- 射出成型課 + 人員主檔：MySQL → Supabase (PostgreSQL) 建表
-- 使用方式：Supabase 後台 → SQL Editor → 整份貼上 → Run
-- =====================================================================

-- ---------------------------------------------------------------------
-- 共用函式：取代 MySQL 的 ON UPDATE CURRENT_TIMESTAMP
-- ---------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


-- ---------------------------------------------------------------------
-- 1. 不良原因
-- ---------------------------------------------------------------------
create table public.im_company_defect_reason (
  id            integer generated by default as identity primary key,
  defect_code   varchar(50)  not null,
  defect_reason varchar(255) not null,
  is_active     boolean      not null default true,
  sort_order    integer      not null default 0,
  remark        text,
  created_at    timestamptz  not null default now(),
  updated_at    timestamptz  not null default now(),
  constraint uk_defect_code_department unique (defect_code)
);
create index idx_defect_active on public.im_company_defect_reason (is_active);

comment on table  public.im_company_defect_reason is '射出成型課 不良原因';
comment on column public.im_company_defect_reason.defect_code   is '不良代碼';
comment on column public.im_company_defect_reason.defect_reason is '不良原因';
comment on column public.im_company_defect_reason.is_active     is '是否啟用';
comment on column public.im_company_defect_reason.sort_order    is '排序順序';
comment on column public.im_company_defect_reason.remark        is '備註';
comment on column public.im_company_defect_reason.created_at    is '建立時間';
comment on column public.im_company_defect_reason.updated_at    is '更新時間';

create trigger trg_im_company_defect_reason_updated_at
  before update on public.im_company_defect_reason
  for each row execute function public.set_updated_at();


-- ---------------------------------------------------------------------
-- 2. 日報主表
-- ---------------------------------------------------------------------
create table public.im_daily_report (
  id                   bigint generated by default as identity primary key,
  report_date          date          not null,
  machine_id           varchar(50)   not null,
  order_no             varchar(100)  not null,
  part_no              varchar(100),
  day_output_qty       integer       default 0,
  day_defect_qty       integer       default 0,
  night_output_qty     integer       default 0,
  night_defect_qty     integer       default 0,
  total_output_qty     integer       default 0,
  prev_accum_qty       integer       default 0,
  today_accum_qty      integer       default 0,
  remaining_target_qty integer       default 0,
  avg_efficiency       numeric(10,2) default 0.00,
  defects_text         text,
  created_at           timestamptz   default now(),
  updated_at           timestamptz   default now()
);

comment on table  public.im_daily_report is '射出成型課 日報主表';
comment on column public.im_daily_report.report_date          is '生產日期';
comment on column public.im_daily_report.machine_id           is '工單號碼';
comment on column public.im_daily_report.order_no             is '製令工單';
comment on column public.im_daily_report.part_no              is '料號';
comment on column public.im_daily_report.day_output_qty       is '日班產量';
comment on column public.im_daily_report.day_defect_qty       is '日班不良數';
comment on column public.im_daily_report.night_output_qty     is '夜班產量';
comment on column public.im_daily_report.night_defect_qty     is '夜班不良數';
comment on column public.im_daily_report.total_output_qty     is '總產量數量';
comment on column public.im_daily_report.prev_accum_qty       is '先前累積數量';
comment on column public.im_daily_report.today_accum_qty      is '今日累計數量';
comment on column public.im_daily_report.remaining_target_qty is '剩餘目標數量';
comment on column public.im_daily_report.avg_efficiency       is '平均效率';
comment on column public.im_daily_report.defects_text         is '不良資訊';
comment on column public.im_daily_report.created_at           is '建立時間';
comment on column public.im_daily_report.updated_at           is '更新時間';

create trigger trg_im_daily_report_updated_at
  before update on public.im_daily_report
  for each row execute function public.set_updated_at();


-- ---------------------------------------------------------------------
-- 3. 不良明細
-- ---------------------------------------------------------------------
create table public.im_daily_report_defect (
  id            bigint generated by default as identity primary key,
  report_id     bigint       not null
                references public.im_daily_report (id)
                on update no action on delete no action,
  shift_type    varchar(10)  not null check (shift_type in ('day', 'night')),
  defect_code   varchar(50)  not null,
  defect_reason varchar(255),
  defect_qty    integer      default 0,
  created_at    timestamptz  default now()
);
create index idx_im_daily_report_defect_report_id on public.im_daily_report_defect (report_id);

comment on table  public.im_daily_report_defect is '射出成型課 不良明細';
comment on column public.im_daily_report_defect.report_id     is '編號';
comment on column public.im_daily_report_defect.shift_type    is '班別';
comment on column public.im_daily_report_defect.defect_code   is '不良代碼';
comment on column public.im_daily_report_defect.defect_reason is '不良原因';
comment on column public.im_daily_report_defect.defect_qty    is '不良數量';
comment on column public.im_daily_report_defect.created_at    is '更新時間';


-- ---------------------------------------------------------------------
-- 4. 班別明細
-- ---------------------------------------------------------------------
create table public.im_daily_report_shift (
  id              bigint generated by default as identity primary key,
  report_id       bigint        not null
                  references public.im_daily_report (id)
                  on update no action on delete no action,
  shift_type      varchar(10)   not null check (shift_type in ('day', 'night')),
  emp_ids         varchar(255),
  prev_molds      integer       default 0,
  cur_molds       integer       default 0,
  actual_cycle    numeric(10,2) default 0.00,
  good_qty        integer       default 0,
  unprocessed_qty integer       default 0,
  setup_qty       integer       default 0,
  pending_qty     integer       default 0,
  plan_hours      numeric(10,2) default 0.00,
  actual_hours    numeric(10,2) default 0.00,
  downtime_hours  numeric(10,2) default 0.00,
  created_at      timestamptz   default now()
);
create index idx_im_daily_report_shift_report_id on public.im_daily_report_shift (report_id);

comment on table  public.im_daily_report_shift is '射出成型課 班別明細';
comment on column public.im_daily_report_shift.report_id       is '編號';
comment on column public.im_daily_report_shift.shift_type      is '班別';
comment on column public.im_daily_report_shift.emp_ids         is '員工編號';
comment on column public.im_daily_report_shift.prev_molds      is '模具號碼';
comment on column public.im_daily_report_shift.good_qty        is '良品數';
comment on column public.im_daily_report_shift.unprocessed_qty is '未處理數';
comment on column public.im_daily_report_shift.pending_qty     is '待處理數';
comment on column public.im_daily_report_shift.plan_hours      is '計畫工時';
comment on column public.im_daily_report_shift.actual_hours    is '實際工時';
comment on column public.im_daily_report_shift.downtime_hours  is '停機時間';
comment on column public.im_daily_report_shift.created_at      is '更新時間';


-- ---------------------------------------------------------------------
-- 5. 機台資料（欄位保留原本大小寫，前端程式不用改欄位名）
-- ---------------------------------------------------------------------
create table public.im_machine (
  "id"             integer generated by default as identity primary key,
  "Machine_Number" integer,
  "Machine_Name"   varchar(50),
  "Machine_Sort"   varchar(50),
  "Brand"          varchar(50),
  "Specification"  varchar(50),
  "Tonnes"         varchar(50),
  "created_at"     timestamptz default now(),
  "updated_at"     timestamptz default now()
);

comment on table  public.im_machine is '射出成型課 機台資料';
comment on column public.im_machine."Machine_Number" is '機台編號';
comment on column public.im_machine."Machine_Name"   is '機台名稱';
comment on column public.im_machine."Machine_Sort"   is '機台分類';
comment on column public.im_machine."Brand"          is '品牌';
comment on column public.im_machine."Specification"  is '規格';
comment on column public.im_machine."Tonnes"         is '噸數';
comment on column public.im_machine."created_at"     is '建立時間';
comment on column public.im_machine."updated_at"     is '更新時間';

create trigger trg_im_machine_updated_at
  before update on public.im_machine
  for each row execute function public.set_updated_at();


-- ---------------------------------------------------------------------
-- 6. 製令工單（欄位保留原本大小寫）
-- ---------------------------------------------------------------------
create table public.im_production_number (
  "idWorkOrder"                integer generated by default as identity primary key,
  "Production_Number"          varchar(50) not null,
  "Master_Parts_Number"        varchar(255),
  "Component_Number"           varchar(255),
  "Product_Name_Specification" varchar(255),
  "Reserve_Completion_Day"     date,
  "Mold_Number"                varchar(255),
  "Number_Of_Holes"            integer       default 1,
  "Cycle"                      numeric(10,2) default 20.00,
  "Production_Quantity"        integer       default 0,
  "Unit_Dosage"                numeric(10,4) default 0.0000,
  constraint uk_im_production_number_new_production_number unique ("Production_Number")
);

comment on table  public.im_production_number is '射出成型課 製令工單';
comment on column public.im_production_number."Production_Number"          is '製令工單';
comment on column public.im_production_number."Master_Parts_Number"        is '材料號碼';
comment on column public.im_production_number."Component_Number"           is '原材料';
comment on column public.im_production_number."Product_Name_Specification" is '品名規格';
comment on column public.im_production_number."Reserve_Completion_Day"     is '到期日';
comment on column public.im_production_number."Mold_Number"                is '模具編號';
comment on column public.im_production_number."Number_Of_Holes"            is '穴數';
comment on column public.im_production_number."Cycle"                      is '標準週期';
comment on column public.im_production_number."Production_Quantity"        is '目標數量';
comment on column public.im_production_number."Unit_Dosage"                is '單位用量';


-- ---------------------------------------------------------------------
-- 7. 人員主檔
-- ---------------------------------------------------------------------
create table public.company_personnel (
  id         integer generated by default as identity primary key,
  emp_id     varchar(50)  not null,
  name       varchar(100) not null,
  department varchar(100) not null,
  unit       varchar(100),
  role_title varchar(100),
  phone      varchar(30),
  email      varchar(255),
  is_active  boolean      not null default true,
  remark     text,
  created_at timestamptz  not null default now(),
  updated_at timestamptz  not null default now(),
  constraint uk_company_personnel_emp_id unique (emp_id)
);
create index idx_company_personnel_department_unit on public.company_personnel (department, unit);
create index idx_company_personnel_active on public.company_personnel (is_active);

comment on table  public.company_personnel is '人員主檔 全公司人員主檔，依單位/部門區分';
comment on column public.company_personnel.emp_id     is '工號';
comment on column public.company_personnel.name       is '姓名';
comment on column public.company_personnel.department is '部門';
comment on column public.company_personnel.unit       is '單位';
comment on column public.company_personnel.role_title is '職務';
comment on column public.company_personnel.phone      is '電話';
comment on column public.company_personnel.email      is '電子郵件';
comment on column public.company_personnel.is_active  is '啟用';
comment on column public.company_personnel.remark     is '備註';
comment on column public.company_personnel.created_at is '建立時間';
comment on column public.company_personnel.updated_at is '更新時間';

create trigger trg_company_personnel_updated_at
  before update on public.company_personnel
  for each row execute function public.set_updated_at();


-- ---------------------------------------------------------------------
-- 權限：讓前端 supabase-js 可直接新增 / 查詢 / 編輯 / 刪除
-- ⚠ 目前為「先能運作」版本：任何拿到網址 + anon key 的人都能改資料。
--   之後加上登入功能時，把 anon 從政策中拿掉即可（見文末）。
-- ---------------------------------------------------------------------
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

do $$
declare
  t text;
begin
  foreach t in array array[
    'im_company_defect_reason',
    'im_daily_report',
    'im_daily_report_defect',
    'im_daily_report_shift',
    'im_machine',
    'im_production_number',
    'company_personnel'
  ]
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format(
      'create policy "allow_all_crud" on public.%I for all to anon, authenticated using (true) with check (true)',
      t
    );
  end loop;
end;
$$;

-- 之後改成「登入者才能操作」時執行（每張表各一次）：
-- alter policy "allow_all_crud" on public.im_machine to authenticated;
